;;; cube-agents-test.el --- Tests for standing agents  -*- lexical-binding: t; -*-

;;; Code:

(require 'cube-test-helper)

(defun cube-agent-test--coordinator ()
  "Return the coordinator from the standing-agent fixture."
  (cube-test-read-fixture "agent-show.json"))

(ert-deftest cube-agent-list-row-renders-identity-and-usage ()
  (let* ((agents (cube-test-read-fixture "agents.json"))
         (coordinator (car agents))
         (expert (cadr agents))
         (row (cube-agent--row-item coordinator))
         (text (plist-get row :label)))
    (should (= (length agents) 3))
    (should (eq (plist-get row :type) 'agent))
    (should (equal (plist-get row :id) "coordinator"))
    (should (string-match-p "◎ coordinator" text))
    (should (string-match-p "Group coordinator" text))
    (should (string-match-p "idle" text))
    (should (string-match-p "proposals 1" text))
    (should (string-match-p "inbox 2" text))
    (should (string-match-p "↩" text))
    (should (string-match-p "journal [0-9]+[hd]" text))
    (should (string-match-p "gpu 1.5h" text))
    (should (string-match-p "● literature" (plist-get (cube-agent--row-item expert) :label)))))

(ert-deftest cube-agent-detail-buffer-renders-groups-and-orders-inbox ()
  (let ((buffer (get-buffer-create "*cube-agent: test*"))
        (agent (cube-agent-test--coordinator)))
    (unwind-protect
        (with-current-buffer buffer
          (cube-agent-mode)
          (setq cube-agent--agent agent)
          (cube-agent--render)
          (let ((text (buffer-string)))
            (should (string-match-p "◎ coordinator  Group coordinator" text))
            (should (string-match-p "Topics: group planning, research priorities" text))
            (should (string-match-p "Charter" text))
            (should (string-match-p "Inbox  \\[unread first\\] (3)" text))
            (should (< (string-match "Review the mitochondrial" text)
                       (string-match "Prepare the Monday" text)))
            (should (string-match-p "Proposals (1)" text))
            (should (string-match-p "cube-501" text))
            (should (string-match-p "Journal (2)" text))
            (should (string-match-p "Resources" text))
            (should (string-match-p "GPU hours.*1.5/4" text))
            (should (string-match-p "Session (1)" text))))
      (kill-buffer buffer))))

(ert-deftest cube-agent-request-group-renders-and-opens-the-request-bead ()
  (let ((buffer (get-buffer-create "*cube-agent: liaison-test*"))
        (agent (cube-test-read-fixture "agent-liaison-show.json"))
        (opened nil))
    (unwind-protect
        (cl-letf (((symbol-function 'cube-beads-show) (lambda (id) (setq opened id))))
          (with-current-buffer buffer
            (cube-agent-mode)
            (setq cube-agent--agent agent)
            (cube-agent--render)
            (should (string-match-p "Requests (1)" (buffer-string)))
            (should (string-match-p "cube-612  Extract ideas from the email I just sent  open  1h"
                                    (buffer-string)))
            (goto-char (point-min))
            (re-search-forward "cube-612")
            (cube-agent-visit)
            (should (equal opened "cube-612"))))
      (kill-buffer buffer))))

(ert-deftest cube-agent-return-glyph-clears-after-its-request-is-viewed ()
  (let* ((coordinator (car (cube-test-read-fixture "agents.json")))
         (request (car (cube-agent--requests coordinator)))
         (cube-agent--viewed-request-ids (make-hash-table :test #'equal)))
    (should (string-match-p "↩" (cube-agent--row-text coordinator)))
    (cube-agent--mark-request-viewed request)
    (should-not (string-match-p "↩" (cube-agent--row-text coordinator)))))

(ert-deftest cube-agent-arguments-and-dry-run-gate ()
  (should (equal (cube-agent--talk-args "coordinator")
                 '("agent" "talk" "coordinator" "--apply" "--attach")))
  (should (equal (cube-agent--tell-args "coordinator" "Read this")
                 '("agent" "tell" "coordinator" "Read this" "--from" "robert" "--apply")))
  (should (string-match-p "queued" (cube-agent--tell-outcome
                                     "coordinator" '((delivery . ((delivered . :json-false)))))))
  (should (string-match-p "live session" (cube-agent--tell-outcome
                                           "coordinator" '((delivery . ((delivered . t)))))))
  (should (equal (cube-agent--workday-args "coordinator")
                 '("agent" "workday" "coordinator" "--now" "--dry-run")))
  (should (equal (cube-agent--pause-args "coordinator" nil "--apply")
                 '("agent" "pause" "coordinator" "--apply")))
  (let ((calls nil) (cube-agents-confirm-writes t))
    (cl-letf (((symbol-function 'cube--call-json-async)
               (lambda (args callback &optional _error)
                 (push args calls)
                 (funcall callback '((ok . t)))))
              ((symbol-function 'cube-agent--show-plan) (lambda (&rest _) nil))
              ((symbol-function 'y-or-n-p) (lambda (_prompt) nil)))
      (cube-agent--write (cube-agent--workday-args "coordinator") "workday coordinator"))
    (should (= (length calls) 1))
    (should (equal (car calls)
                   '("agent" "workday" "coordinator" "--now" "--dry-run")))))

(ert-deftest cube-agent-talk-and-tell-use-the-agent-host ()
  (let ((starts nil) (calls nil) (opened nil)
        (cube-agent--cache (cube-test-read-fixture "agents.json")))
    (cl-letf (((symbol-function 'cube-rolodex-start)
               (lambda (&rest args) (push (cons cube-remote-host args) starts)))
              ((symbol-function 'cube--call-json-async-on)
               (lambda (host args callback &optional _error)
                 (push (cons host args) calls)
                 (funcall callback '((ok . t)))))
              ((symbol-function 'cube-agent-open)
               (lambda (name) (setq opened name))))
      (cube-agent-talk)
      (cube-agent-talk nil "liaison")
      (let ((cube-agent-tell-wakes nil))
        (cube-agent-tell "liaison" "Compare these papers")
        (cube-agent-tell "coordinator" "Coordinate this")))
    (setq starts (nreverse starts)
          calls (nreverse calls))
    (should (equal (mapcar #'car starts) '("ws" nil)))
    (should (equal (mapcar (lambda (start) (seq-take (cdr start) 2)) starts)
                   '((agent "coordinator") (agent "liaison"))))
    (should-not (caar calls))
    (should (equal (cdar calls)
                   '("agent" "tell" "liaison" "Compare these papers"
                     "--from" "robert" "--apply")))
    (should (equal (caadr calls) "ws"))
    (should (equal (cdadr calls)
                   '("agent" "tell" "coordinator" "Coordinate this"
                     "--from" "robert" "--apply")))
    (should (equal opened "coordinator"))))

(ert-deftest cube-ask-coordinator-sends-the-coordinator-tell-arguments ()
  (let ((calls nil)
        (cube-agent--cache (cube-test-read-fixture "agents.json")))
    (cl-letf (((symbol-function 'cube--call-json-async-on)
               (lambda (host args callback &optional _error)
                 (setq calls (list host args))
                 (funcall callback '((delivery . ((delivered . t)))))))
              ((symbol-function 'cube-agent-open) #'ignore))
      (cube-ask-coordinator "Please check the email ideas"))
    (should (equal calls
                   '("ws" ("agent" "tell" "coordinator" "Please check the email ideas"
                           "--from" "robert" "--apply"))))))

(ert-deftest cube-agent-new-arguments-and-mode-keys ()
  (should (equal
           (cube-agent--new-args
            '(:name "papers" :kind "expert" :title "Reading expert"
              :topics ("read papers" "literature") :role "editor"
              :runtime "claude" :from-template t))
           '("agent" "new" "papers" "--kind" "expert" "--title" "Reading expert"
             "--topic" "read papers" "--topic" "literature" "--role" "editor"
             "--runtime" "claude" "--from-template" "--dry-run")))
  (dolist (pair '(("RET" . cube-agent-visit) ("T" . cube-agent-talk)
                  ("t" . cube-agent-tell) ("w" . cube-agent-workday)
                  ("p" . cube-agent-pause-resume) ("r" . cube-agent-report)
                  ("e" . cube-agent-edit-charter) ("a" . cube-agent-approve)))
    (should (eq (lookup-key cube-agent-mode-map (kbd (car pair))) (cdr pair))))
  (should (get 'cube-agent-new-menu 'transient--prefix)))

(ert-deftest cube-agent-menu-and-rolodex-surface-standing-agents ()
  (let ((cube-agent--cache (cube-test-read-fixture "agents.json")))
    (let* ((menu (cube-menu--global-menu))
           (agents (seq-find (lambda (item) (and (listp item)
                                                 (equal (car item) "Agents")))
                             (cdr menu)))
           (filtered (cube-menu--agents-filter (cdr agents))))
      (should agents)
      (should (string-match-p "◎ coordinator" (prin1-to-string filtered)))
      (should (string-match-p "● literature" (prin1-to-string filtered)))
      (should (cube-menu--context-items 'agent)))
    (let* ((coordinator (cube-session-create :name "coordinator" :kind 'agent
                                             :agent-kind "coordinator" :state 'idle))
           (expert (cube-session-create :name "literature" :kind 'agent
                                        :agent-kind "expert" :state 'running))
           (ordinary (cube-session-create :name "shell" :kind 'shell :state 'attention))
           (ordered (cube-rolodex--ordered (list ordinary expert coordinator))))
      (should (equal (mapcar #'cube-session-name ordered)
                     '("coordinator" "literature" "shell")))
      (should (equal (cube-rolodex--label coordinator) "◎ coordinator"))
      (should (equal (cube-rolodex--label expert) "● literature")))))

(provide 'cube-agents-test)
;;; cube-agents-test.el ends here

(ert-deftest cube-agent-tell-wakes-a-sleeping-agent-and-not-a-live-one ()
  (let ((starts nil) (opened nil) (calls nil)
        (json '((delivery . ((delivered . :json-false)))))
        (cube-agent--cache (cube-test-read-fixture "agents.json")))
    (cl-letf (((symbol-function 'cube-rolodex-start)
               (lambda (&rest args) (push args starts)))
              ((symbol-function 'cube-rolodex-find) (lambda (_name) nil))
              ((symbol-function 'run-with-timer)
               (lambda (_secs _repeat fn &rest args) (apply fn args)))
              ((symbol-function 'cube--call-json-async-on)
               (lambda (_host args callback &optional _error)
                 (push args calls)
                 (funcall callback json)))
              ((symbol-function 'cube-agent-open)
               (lambda (name) (setq opened name))))
      (let ((cube-agent-tell-wakes t))
        (cube-agent-tell "coordinator" "Check my email"))
      (should (equal (seq-take (car starts) 2) '(agent "coordinator")))
      ;; queued, woken, then delivered again into the fresh session
      (should (= (length calls) 2))
      ;; the wake re-delivery must not append to the inbox a second time
      (should (equal (car calls)
                     '("agent" "tell" "coordinator" "Check my email" "--from" "robert" "--apply"
                       "--redeliver")))
      (should (equal (cadr calls)
                     '("agent" "tell" "coordinator" "Check my email" "--from" "robert" "--apply")))
      (should-not opened)
      (setq json '((delivery . ((delivered . t)))))
      (let ((cube-agent-tell-wakes t))
        (cube-agent-tell "coordinator" "Check my email"))
      (should (= (length starts) 1))
      (should (equal opened "coordinator")))))
