"use strict";
(() => {
  const $ = (id) => document.getElementById(id);
  const state = {snapshot:null, detail:null, selected:null, tab:"overview", loading:false, request:0, csrf:null, triggerBusy:false, drafts:new Map(), triggerNotices:new Map()};
  const number = (value) => value == null ? "Unavailable" : new Intl.NumberFormat().format(value);
  const money = (value) => value == null ? "Unavailable" : new Intl.NumberFormat(undefined,{style:"currency",currency:"USD",maximumFractionDigits:3}).format(value);
  const duration = (value) => value == null ? "Unavailable" : `${Math.floor(Math.max(0,value)/3600)}h ${Math.floor(Math.max(0,value)%3600/60)}m`;
  const date = (value) => { if (!value) return "Unknown"; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? String(value) : parsed.toLocaleString(); };
  function el(tag, text, className) { const node=document.createElement(tag); if(text!=null) node.textContent=String(text); if(className) node.className=className; return node; }
  function empty(text) { return el("p",text,"empty"); }
  function showError(error) { $("error").textContent=`${error.message || error} Use Refresh to retry. No action will be retried automatically.`; $("error").hidden=false; }
  async function api(path, options={}) { const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),20000);try {const response=await fetch(path,{credentials:"same-origin",cache:"no-store",signal:controller.signal,...options}); let data; try {data=await response.json();} catch {throw new Error(`Server returned ${response.status}; check the explorer service on ws.`);} if(!response.ok) throw new Error(data.error || data.detail || `Request failed (${response.status})`); return data;}catch(error){if(error.name==="AbortError")throw new Error("The server did not respond in 20 seconds. A submitted trigger may still be running; inspect its status before submitting another.");throw error;}finally{clearTimeout(timeout);} }
  function status(node, value) { const label=String(value || "unknown"); node.textContent=label; node.className="state"; if(["busy","running","failed","blocked"].includes(label)) node.classList.add(label); }
  function statFields(node,fields) {node.replaceChildren();for(const [name,value] of fields){const item=el("div",null,"stat");item.append(el("dt",name),el("dd",value));node.append(item);}}
  function stats(node,data) {statFields(node,[["Runs",number(data.run_count)],["Tokens",number(data.total_tokens)],[data.api_calls_missing ? "API calls (partial)" : "API calls",number(data.api_calls)],["Recorded cost",money(data.cost_usd)],["Equivalent cost",money(data.equivalent_usd)],["Recorded run time",duration(data.duration_seconds)]]);const runtime=node.lastElementChild;runtime.title="Sum of finished run walltimes, not CPU time or utilization.";runtime.append(el("small","Finished walltimes, not CPU time"));}
  function tokenBreakdown(data) {return `Input ${number(data.input_tokens)} / output ${number(data.output_tokens)} / cache read ${number(data.cache_read_tokens)} / cache write ${number(data.cache_write_tokens)} tokens`;}
  function charterText(text) {return String(text || "").replace(/^\uFEFF?---\s*\r?\n[\s\S]*?\r?\n(?:---|\.\.\.)\s*(?:\r?\n|$)/, "").trim();}
  function gatewaySection(data) {const block=el("section",null,"subsection");block.append(el("h3","Gateway sessions"),el("p","Lifetime session counters for sessions active in this time window. These are separate from fleet workday totals.","prose muted"));const metrics=el("dl",null,"stats");statFields(metrics,[["Sessions",number(data.sessions)],["API calls",number(data.api_calls)],["Actual cost",money(data.actual_cost_usd)],["Estimated cost",money(data.estimated_cost_usd)]]);block.append(metrics,el("p",tokenBreakdown(data),"prose muted"),el("p",`Actual-cost coverage: ${number(data.cost_sessions_known)} of ${number(data.sessions)} sessions.`,"source"));if(data.note)block.append(el("p",data.note,"prose muted"));if(data.source)block.append(el("p",data.source,"source"));return block;}
  function warnings() { const items=[...(state.snapshot?.warnings || []),...(state.detail?.warnings || [])]; if(state.snapshot?.kill) items.unshift("Fleet stop switch is active. Agent triggers are disabled."); if(state.snapshot?.totals?.usage_missing) items.push(`${number(state.snapshot.totals.usage_missing)} fleet runs have incomplete usage telemetry. Totals may be partial.`); if(state.detail?.agent?.usage_missing) items.push(`${number(state.detail.agent.usage_missing)} selected-agent runs have incomplete usage telemetry.`);if(state.snapshot?.totals?.api_calls_missing)items.push(`API-call counts are missing for ${number(state.snapshot.totals.api_calls_missing)} fleet runs. Displayed API counts include known calls only.`);if(state.detail?.agent?.api_calls_missing)items.push(`API-call counts are missing for ${number(state.detail.agent.api_calls_missing)} selected-agent runs.`);if(state.snapshot?.unattributed_runs>0)items.push(`${number(state.snapshot.unattributed_runs)} runs have no agent attribution. Fleet totals include these runs, so agent totals may not add up to the fleet total.`); $("warnings").replaceChildren(...[...new Set(items.map(String))].map(text=>el("p",text))); $("warnings").hidden=!items.length; }
  function roster() { const query=$("search").value.toLowerCase(); const all=state.snapshot?.agents || []; $("agent-count").textContent=number(all.length); const list=all.filter(a=>`${a.name} ${a.title} ${a.role} ${a.host}`.toLowerCase().includes(query)); $("agents").replaceChildren(); for(const agent of list){const button=el("button",null,"agent");button.type="button";button.setAttribute("aria-pressed",String(agent.name===state.selected));button.append(el("span",agent.title || agent.name,"agent-name")); const meta=el("span",null,"agent-meta"), badge=el("span");status(badge,agent.state);meta.append(badge,el("span",`${number(agent.run_count)} runs`));button.append(meta);button.title=`${agent.name}: ${agent.role} on ${agent.host}`;button.addEventListener("click",()=>selectAgent(agent.name));$("agents").append(button);} if(!list.length) $("agents").append(empty(query ? "No agents match this search." : "No agents are registered on this host.")); }
  function timeline() { const rows=state.snapshot?.timeline || [], metric=$("metric").value, max=Math.max(1,...rows.map(r=>Number(r[metric]) || 0));$("chart").replaceChildren();$("chart-labels").replaceChildren();if(!rows.length){$("chart").append(empty("No runs recorded in this time window."));return;} for(const row of rows){const value=Number(row[metric]) || 0, column=el("div",null,"chart-column"),bar=el("div",null,"chart-bar");column.tabIndex=0;column.dataset.value=String(value);column.setAttribute("role","img");column.setAttribute("aria-label",`${row.date}: ${number(value)} ${metric==="run_count"?"runs":"tokens"}`);column.title=column.getAttribute("aria-label");bar.style.height=`${Math.max(0,value/max*100)}%`;column.append(bar);$("chart").append(column);} $("chart-labels").append(el("span",rows[0].date),el("span",rows[rows.length-1].date)); }
  function section(title,text) {const block=el("section",null,"subsection");block.append(el("h3",title),el("p",text || "Nothing recorded yet.","prose"));return block;}
  function triggerPanel(agent) {const panel=el("section",null,"trigger-panel");panel.append(el("h3","Run this agent"),el("p","Start one work cycle within its existing permissions and resource limits."));const label=el("label","Optional instruction");label.htmlFor="trigger-message";const input=el("textarea");input.id="trigger-message";input.maxLength=4000;input.rows=3;input.value=state.drafts.get(agent.name) || "";input.placeholder="Focus this cycle on...";input.addEventListener("input",()=>state.drafts.set(agent.name,input.value));const button=el("button",state.triggerBusy?"Requesting run...":"Run one cycle","primary");button.type="button";button.disabled=!agent.can_trigger || Boolean(state.snapshot?.kill) || state.triggerBusy;button.addEventListener("click",()=>trigger(agent,input.value));panel.append(label,input,button);if(!agent.can_trigger) panel.append(el("p",agent.reason || "This agent cannot be triggered from this host.","muted"));if(state.detail.trigger) panel.append(el("p",`Last trigger: ${state.detail.trigger.status || "unknown"}`,"muted"));const notice=state.triggerNotices.get(agent.name);if(notice){const feedback=el("p",notice,"source");feedback.setAttribute("role","status");panel.append(feedback);}return panel;}
  function renderDetail() {const data=state.detail;if(!data)return;const a=data.agent;$("detail-name").textContent=a.title || a.name;status($("detail-state"),a.state);$("detail-meta").textContent=`${a.name} / ${a.role} / ${a.host}`;stats($("agent-stats"),a);const root=$("detail");root.replaceChildren();root.setAttribute("aria-labelledby",`tab-${state.tab}`);for(const tab of document.querySelectorAll(".tab")){const active=tab.dataset.tab===state.tab;tab.setAttribute("aria-selected",String(active));tab.tabIndex=active?0:-1;}
    if(state.tab==="overview"){const columns=el("div",null,"detail-columns"),content=el("div");content.append(section("Token usage",tokenBreakdown(a)));if(a.name==="hermes-ws" && data.gateway_usage)content.append(gatewaySection(data.gateway_usage));content.append(section("Latest work",a.latest_summary),section("Research scope",charterText(data.charter)));const taskSection=el("section",null,"subsection");taskSection.append(el("h3","Work ledger"));const tasks=el("ul",null,"task-list");for(const task of data.tasks || []){const li=el("li");li.append(el("div",task.title),el("div",`${task.id} / ${task.status}`,"task-meta"));tasks.append(li);}taskSection.append(tasks.children.length?tasks:empty("No current tasks recorded."));content.append(taskSection);columns.append(content,triggerPanel(a));root.append(columns);}
    else if(state.tab==="runs"){const breakdown=el("p",`Input ${number(a.input_tokens)} / output ${number(a.output_tokens)} / cache read ${number(a.cache_read_tokens)} / cache write ${number(a.cache_write_tokens)} tokens`,"muted");root.append(breakdown);if(!(data.runs || []).length){root.append(empty("No runs recorded in this time window."));return;}const wrap=el("div",null,"table-wrap"),table=el("table"),head=el("thead"),tr=el("tr");for(const title of ["Run / evidence","State","Tokens","API calls","Cost"])tr.append(el("th",title));head.append(tr);table.append(head);const body=el("tbody");for(const run of data.runs){const row=el("tr"),first=el("td"),details=el("details");details.append(el("summary",date(run.started)),el("p",run.summary || "No summary recorded.","prose"),el("p",`Run: ${run.id}\nRunner: ${run.runner || "unknown"}\nModel: ${run.model || "unknown"}\nFinished: ${date(run.finished)}\nAttribution: ${run.attribution || "not recorded"}\nSource: ${run.source || "not recorded"}`,"prose source"));first.append(details);row.append(first,el("td",run.state),el("td",number(run.total_tokens),"mono"),el("td",number(run.api_calls),"mono"),el("td",money(run.cost_usd),"mono"));body.append(row);}table.append(body);wrap.append(table);root.append(wrap);}
    else {for(const memory of data.memories || []){const item=el("details",null,"memory");item.append(el("summary",memory.name),el("p",memory.text || "Empty memory file.","prose"),el("p",memory.source,"source"));root.append(item);}if(!root.children.length)root.append(empty("No shareable memory is recorded for this agent."));}warnings(); }
  async function selectAgent(name) {state.selected=name;state.detail=null;roster();$("detail-name").textContent=name;$("detail").replaceChildren(empty("Loading agent evidence..."));const request=++state.request;try {const data=await api(`/api/agents/${encodeURIComponent(name)}?days=${$("days").value}`);if(request!==state.request)return;state.detail=data;renderDetail();warnings();}catch(error){if(request===state.request)showError(error);}}
  async function refresh() {if(state.loading)return;state.loading=true;$("refresh").disabled=true;try{const snapshot=await api(`/api/snapshot?days=${$("days").value}`);state.snapshot=snapshot;$("host").textContent=snapshot.host ? `/ ${snapshot.host}` : "";$("updated").textContent=`Updated ${date(snapshot.generated)}`;const busy=snapshot.agents.filter(a=>["busy","running"].includes(a.state)).length;status($("fleet-state"),snapshot.kill?"Stopped":`${busy} active / ${snapshot.agents.length} agents`);stats($("totals"),snapshot.totals);roster();timeline();$("error").hidden=true;const selected=snapshot.agents.find(a=>a.name===state.selected)?.name || snapshot.agents[0]?.name;if(selected){const request=++state.request,data=await api(`/api/agents/${encodeURIComponent(selected)}?days=${$("days").value}`);if(request===state.request){state.selected=selected;state.detail=data;roster();renderDetail();}}warnings();}catch(error){showError(error);}finally{state.loading=false;$("refresh").disabled=false;}}
  async function trigger(agent,message) {if(state.triggerBusy)return;if(!window.confirm(`Run one cycle of ${agent.title || agent.name}?\n\nThis can make API calls and consume the central resource budget. Existing approval boundaries remain in force.${message?`\n\nInstruction: ${message}`:""}`))return;state.triggerBusy=true;renderDetail();try{if(!state.csrf)state.csrf=(await api("/api/session")).csrf;const result=await api(`/api/agents/${encodeURIComponent(agent.name)}/trigger`,{method:"POST",headers:{"Content-Type":"application/json","X-Cube-CSRF":state.csrf},body:JSON.stringify({confirm:true,message})});state.triggerNotices.set(agent.name,`Trigger ${result.status}. Command: ${(result.command || []).join(" ")}`);state.drafts.delete(agent.name);await refresh();}catch(error){showError(error);state.csrf=null;}finally{state.triggerBusy=false;renderDetail();}}
  $("search").addEventListener("input",roster);$("metric").addEventListener("change",timeline);$("days").addEventListener("change",refresh);$("refresh").addEventListener("click",refresh);const tabs=[...document.querySelectorAll(".tab")];for(const tab of tabs){tab.addEventListener("click",()=>{state.tab=tab.dataset.tab;renderDetail();});tab.addEventListener("keydown",event=>{const index=tabs.indexOf(tab);let next;if(event.key==="ArrowRight")next=(index+1)%tabs.length;if(event.key==="ArrowLeft")next=(index+tabs.length-1)%tabs.length;if(event.key==="Home")next=0;if(event.key==="End")next=tabs.length-1;if(next!=null){event.preventDefault();tabs[next].focus();tabs[next].click();}});}setInterval(()=>{if(!document.hidden && !state.triggerBusy && !$("detail").contains(document.activeElement))refresh();},30000);document.addEventListener("visibilitychange",()=>{if(!document.hidden)refresh();});refresh();
})();
